# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Run action"

on:
    push:
        branches:
            - "**"
        paths:
            - ".github/workflows/**"
            - "src/**"
            - "dist/**"
            - "package*.json"
            - "action.yml"

jobs:
    run-action:
        name: "Run action"

        strategy:
            matrix:
                system:
                    - ubuntu-24.04

        runs-on: ${{ matrix.system }}

        steps:
            - name: Print input
              id: echo-action
              uses: imesense/gha-echo-action@default
              with:
                  input-string: "Input"

            - name: Print output
              run: |
                  echo "${{ steps.echo-action.outputs.output-string }}"
