name: 'Run action'

on:
  push:
    branches:
      - '**'

jobs:
  run-action:
    name: 'Run action'

    strategy:
      matrix:
        system:
          - ubuntu-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Print input
        id: echo-action
        uses: imesense/gha-echo-action@8f7adacea666431fa8fa3d2e1022490ccad33325
        with:
          input-string: 'Input'

      - name: Print output
        run: |
          echo "${{ steps.echo-action.outputs.output-string }}"
